apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: devops-tools
spec:
  securityContext:
    fsGroup: 1000
  serviceAccountName: jenkins-sa
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - 99d
  restartPolicy: Never